version = 0.1

[default.deploy.parameters]
stack_name = "baruchtbt-5"
resolve_s3 = true
s3_prefix = "baruchtbt-5"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-west-2"
